apiVersion: v1
kind: LimitRange
metadata:
  name: memlimits
spec:
  limits:
  - default:
      cpu: 100m
      memory: 128Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    max:
      cpu: 200m
      memory: 256Mi
    type: Container
