apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yes-test
  name: yes-test
  namespace: ns-dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: yes-test
  strategy: {}
  template:
    metadata:
      labels:
        app: yes-test
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
status: {}
